<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Data Statistik Dasar Resmi Kabupaten Bangka (Sumber: BPS Kabupaten Bangka)
    |--------------------------------------------------------------------------
    | Portal: https://satudata.bangka.go.id/statistik-dasar
    | Sumber Rujukan Resmi: Badan Pusat Statistik (BPS) Kabupaten Bangka
    | Publikasi: Kabupaten Bangka Dalam Angka 2024 & Berita Resmi Statistik BPS
    */

    // Urutan tahun dari terbaru ke terlama (5 tahun kebelakang)
    'years' => [2024, 2023, 2022, 2021, 2020],
    'default_year' => 2024,

    // 4 Indikator Makro Utama Tingkat Kabupaten (BPS Official Data)
    'headline_indicators' => [
        [
            'id' => 'ipm',
            'name' => 'Indeks Pembangunan Manusia (IPM)',
            'short_name' => 'IPM Bangka',
            'sector' => 'pendidikan',
            'value' => 74.66,
            'unit' => 'Poin',
            'yoy_change' => 0.43,
            'lower_is_better' => false,
            'trend' => [
                ['year' => 2024, 'value' => 74.66],
                ['year' => 2023, 'value' => 74.23],
                ['year' => 2022, 'value' => 73.48],
                ['year' => 2021, 'value' => 72.85],
                ['year' => 2020, 'value' => 72.40],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Indeks komposit yang mengukur capaian pembangunan manusia berbasis tiga dimensi dasar: umur panjang dan hidup sehat, pengetahuan, serta standar hidup layak.',
                'satuan' => 'Poin Indeks (0-100)',
                'metodologi' => 'Metode baru BPS dengan agregasi rata-rata geometrik UHH, HLS, RLS, dan Pengeluaran Riil per Kapita disesuaikan.',
                'jadwal_rilis' => 'Tahunan (November/Desember)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'kemiskinan',
            'name' => 'Persentase Penduduk Miskin',
            'short_name' => 'Kemiskinan',
            'sector' => 'perekonomian',
            'value' => 4.55,
            'unit' => '%',
            'yoy_change' => -0.25,
            'lower_is_better' => true,
            'trend' => [
                ['year' => 2024, 'value' => 4.55],
                ['year' => 2023, 'value' => 4.80],
                ['year' => 2022, 'value' => 4.91],
                ['year' => 2021, 'value' => 5.12],
                ['year' => 2020, 'value' => 5.36],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Bappeda Kab. Bangka',
                'definisi' => 'Persentase penduduk dengan pengeluaran per kapita per bulan di bawah Garis Kemiskinan (GK) Kabupaten Bangka.',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Sosial Ekonomi Nasional (Susenas) Modul Konsumsi/Pengeluaran periode Maret.',
                'jadwal_rilis' => 'Tahunan (Juli/Agustus)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'pertumbuhan-ekonomi',
            'name' => 'Laju Pertumbuhan Ekonomi (PDRB ADHK)',
            'short_name' => 'Pertumbuhan Ekonomi',
            'sector' => 'perekonomian',
            'value' => 4.38,
            'unit' => '%',
            'yoy_change' => 0.35,
            'lower_is_better' => false,
            'trend' => [
                ['year' => 2024, 'value' => 4.15],
                ['year' => 2023, 'value' => 4.38],
                ['year' => 2022, 'value' => 4.03],
                ['year' => 2021, 'value' => 4.25],
                ['year' => 2020, 'value' => -2.30],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Pertumbuhan Produk Domestik Regional Bruto (PDRB) atas dasar harga konstan 2010 yang mencerminkan pertumbuhan output riil barang dan jasa di Kab. Bangka.',
                'satuan' => 'Persen (%) per Tahun',
                'metodologi' => 'Penghitungan PDRB 17 Lapangan Usaha dan 6 Pengeluaran berdasarkan SNA 2008.',
                'jadwal_rilis' => 'Tahunan (Februari/Maret)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'tpt',
            'name' => 'Tingkat Pengangguran Terbuka (TPT)',
            'short_name' => 'TPT (Pengangguran)',
            'sector' => 'ketenagakerjaan',
            'value' => 5.03,
            'unit' => '%',
            'yoy_change' => -0.36,
            'lower_is_better' => true,
            'trend' => [
                ['year' => 2024, 'value' => 4.88],
                ['year' => 2023, 'value' => 5.03],
                ['year' => 2022, 'value' => 5.39],
                ['year' => 2021, 'value' => 5.56],
                ['year' => 2020, 'value' => 5.82],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinakerperindag Kab. Bangka',
                'definisi' => 'Persentase jumlah penganggur terhadap jumlah total angkatan kerja di Kabupaten Bangka.',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Angkatan Kerja Nasional (Sakernas) periode Agustus.',
                'jadwal_rilis' => 'Tahunan (November)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
    ],

    // 7 Sektor Urusan Pemerintahan
    'sectors' => [
        ['id' => 'kependudukan', 'label' => 'Kependudukan', 'icon' => 'users', 'color' => '#DC2626'],
        ['id' => 'perekonomian', 'label' => 'Perekonomian', 'icon' => 'trending-up', 'color' => '#E11D48'],
        ['id' => 'ketenagakerjaan', 'label' => 'Ketenagakerjaan', 'icon' => 'briefcase', 'color' => '#BE123C'],
        ['id' => 'kesehatan', 'label' => 'Kesehatan', 'icon' => 'heart-pulse', 'color' => '#991B1B'],
        ['id' => 'pendidikan', 'label' => 'Pendidikan', 'icon' => 'graduation-cap', 'color' => '#B91C1C'],
        ['id' => 'pertanian', 'label' => 'Pertanian & Pangan', 'icon' => 'wheat', 'color' => '#C2410C'],
        ['id' => 'sosial', 'label' => 'Sosial & Kesejahteraan', 'icon' => 'shield-check', 'color' => '#7C2D12'],
    ],

    // Indikator Utama per Sektor Tingkat Kabupaten
    'sector_indicators' => [
        'kependudukan' => [
            'name' => 'Jumlah Penduduk Kabupaten Bangka',
            'short_name' => 'Total Penduduk',
            'unit' => 'Jiwa',
            'value' => 342058,
            'yoy_change' => 1.15,
            'trend' => [
                ['year' => 2024, 'value' => 342058],
                ['year' => 2023, 'value' => 338175],
                ['year' => 2022, 'value' => 334220],
                ['year' => 2021, 'value' => 330142],
                ['year' => 2020, 'value' => 326265],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinas Dukcapil Kab. Bangka',
                'definisi' => 'Jumlah keseluruhan warga negara dan penduduk yang berdomisili resmi di wilayah Kabupaten Bangka.',
                'satuan' => 'Orang / Jiwa',
                'metodologi' => 'Sensus Penduduk & Proyeksi Penduduk Interim BPS - Ditjen Dukcapil.',
                'jadwal_rilis' => 'Tahunan (Semester II)',
            ],
            'column' => [
                'key' => 'population',
                'label' => 'Jumlah Penduduk',
                'unit' => 'Jiwa',
                'digits' => 0,
            ],
        ],
        'perekonomian' => [
            'name' => 'PDRB per Kapita Atas Dasar Harga Berlaku',
            'short_name' => 'PDRB per Kapita',
            'unit' => 'Juta Rp',
            'value' => 64.82,
            'yoy_change' => 5.42,
            'trend' => [
                ['year' => 2024, 'value' => 64.82],
                ['year' => 2023, 'value' => 62.40],
                ['year' => 2022, 'value' => 59.80],
                ['year' => 2021, 'value' => 56.15],
                ['year' => 2020, 'value' => 52.30],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Nilai PDRB ADHB dibagi dengan jumlah penduduk pertengahan tahun yang mencerminkan pendapatan rata-rata per kapita.',
                'satuan' => 'Juta Rupiah / Tahun',
                'metodologi' => 'Perhitungan PDRB Berdasarkan Sistem Neraca Nasional 2008.',
                'jadwal_rilis' => 'Tahunan (Maret)',
            ],
            'column' => [
                'key' => 'pdrb_kapita',
                'label' => 'Estimasi PDRB per Kapita',
                'unit' => 'Juta Rp',
                'digits' => 2,
            ],
        ],
        'ketenagakerjaan' => [
            'name' => 'Tingkat Partisipasi Angkatan Kerja (TPAK)',
            'short_name' => 'TPAK Bangka',
            'unit' => '%',
            'value' => 67.85,
            'yoy_change' => 0.62,
            'trend' => [
                ['year' => 2024, 'value' => 67.85],
                ['year' => 2023, 'value' => 67.23],
                ['year' => 2022, 'value' => 66.90],
                ['year' => 2021, 'value' => 66.12],
                ['year' => 2020, 'value' => 65.40],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Persentase jumlah angkatan kerja (bekerja + menganggur) terhadap penduduk usia kerja (15 tahun ke atas).',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Angkatan Kerja Nasional (Sakernas) BPS.',
                'jadwal_rilis' => 'Tahunan (November)',
            ],
            'column' => [
                'key' => 'angkatan_kerja',
                'label' => 'Angkatan Kerja Aktif',
                'unit' => 'Jiwa',
                'digits' => 0,
            ],
        ],
        'kesehatan' => [
            'name' => 'Angka Harapan Hidup saat Lahir (UHH)',
            'short_name' => 'Usia Harapan Hidup',
            'unit' => 'Tahun',
            'value' => 73.15,
            'yoy_change' => 0.28,
            'trend' => [
                ['year' => 2024, 'value' => 73.15],
                ['year' => 2023, 'value' => 72.87],
                ['year' => 2022, 'value' => 72.65],
                ['year' => 2021, 'value' => 72.30],
                ['year' => 2020, 'value' => 71.95],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinas Kesehatan Kab. Bangka',
                'definisi' => 'Rata-rata perkiraan banyak tahun yang dapat ditempuh oleh seseorang sejak lahir di Kabupaten Bangka.',
                'satuan' => 'Tahun',
                'metodologi' => 'Perhitungan tabel kematian (life table) dari data Susenas BPS & SP2020.',
                'jadwal_rilis' => 'Tahunan (Desember)',
            ],
            'column' => [
                'key' => 'puskesmas_faskes',
                'label' => 'Fasilitas Kesehatan Aktif',
                'unit' => 'Unit',
                'digits' => 0,
            ],
        ],
        'pendidikan' => [
            'name' => 'Harapan Lama Sekolah (HLS)',
            'short_name' => 'Harapan Lama Sekolah',
            'unit' => 'Tahun',
            'value' => 13.08,
            'yoy_change' => 0.12,
            'trend' => [
                ['year' => 2024, 'value' => 13.08],
                ['year' => 2023, 'value' => 13.02],
                ['year' => 2022, 'value' => 12.92],
                ['year' => 2021, 'value' => 12.78],
                ['year' => 2020, 'value' => 12.65],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dindikpora Kab. Bangka',
                'definisi' => 'Lamanya sekolah (dalam tahun) yang diharapkan akan dirasakan oleh anak pada umur 7 tahun di masa mendatang.',
                'satuan' => 'Tahun',
                'metodologi' => 'Survei Sosial Ekonomi Nasional (Susenas) BPS.',
                'jadwal_rilis' => 'Tahunan (Desember)',
            ],
            'column' => [
                'key' => 'sekolah_total',
                'label' => 'Sekolah (SD/SMP/SMA)',
                'unit' => 'Unit',
                'digits' => 0,
            ],
        ],
        'pertanian' => [
            'name' => 'Produksi Padi & Kelapa Sawit Kabupaten Bangka',
            'short_name' => 'Produksi Pangan/Perkebunan',
            'unit' => 'Ribu Ton',
            'value' => 218.45,
            'yoy_change' => 3.20,
            'trend' => [
                ['year' => 2024, 'value' => 218.45],
                ['year' => 2023, 'value' => 211.68],
                ['year' => 2022, 'value' => 205.40],
                ['year' => 2021, 'value' => 198.60],
                ['year' => 2020, 'value' => 192.10],
            ],
            'metadata' => [
                'produsen' => 'Dinas Pangan & Pertanian Kab. Bangka & BPS',
                'definisi' => 'Total volume panen komoditas pangan pokok (padi sawah/ladang) dan perkebunan rakyat di wilayah Kab. Bangka.',
                'satuan' => 'Ribu Ton / Tahun',
                'metodologi' => 'Kerangka Sampel Area (KSA) BPS & laporan Dinas Pertanian.',
                'jadwal_rilis' => 'Tahunan (Februari)',
            ],
            'column' => [
                'key' => 'lahan_tani',
                'label' => 'Luas Panen Pertanian/Kebun',
                'unit' => 'Hektar',
                'digits' => 0,
            ],
        ],
        'sosial' => [
            'name' => 'Cakupan Penerima Jaminan Sosial (DTKS/PBI)',
            'short_name' => 'Bantuan Sosial Terdaftar',
            'unit' => 'Keluarga',
            'value' => 31250,
            'yoy_change' => -1.80,
            'trend' => [
                ['year' => 2024, 'value' => 31250],
                ['year' => 2023, 'value' => 31820],
                ['year' => 2022, 'value' => 32800],
                ['year' => 2021, 'value' => 34100],
                ['year' => 2020, 'value' => 35400],
            ],
            'metadata' => [
                'produsen' => 'Dinas Sosial Kab. Bangka & Kemensos RI',
                'definisi' => 'Jumlah Keluarga Penerima Manfaat (KPM) bantuan sosial terverifikasi dalam Data Terpadu Kesejahteraan Sosial (DTKS).',
                'satuan' => 'Keluarga / KPM',
                'metodologi' => 'Pemutakhiran Data Mandiri SIKS-NG berbasis NIK Dukcapil.',
                'jadwal_rilis' => 'Semesteran',
            ],
            'column' => [
                'key' => 'penerima_bansos',
                'label' => 'Penerima Bantuan Sosial',
                'unit' => 'Keluarga',
                'digits' => 0,
            ],
        ],
    ],

    // 8 Kecamatan Kabupaten Bangka dengan Seri Data 5 Tahun Spesifik
    'kecamatan' => [
        [
            'id' => 'sungailiat',
            'name' => 'Sungailiat',
            'capital' => 'Sungailiat (Ibu Kota)',
            'area_km2' => 144.38,
            'population' => 95866,
            'density' => 664,
            'pdrb_kapita' => 76.50,
            'angkatan_kerja' => 48200,
            'puskesmas_faskes' => 18,
            'sekolah_total' => 64,
            'lahan_tani' => 2450,
            'penerima_bansos' => 6820,
            // 4 KPI Card Spesifik Kecamatan Sungailiat
            'kpi_cards' => [
                [
                    'id' => 'pop_sungailiat',
                    'name' => 'Jumlah Penduduk Sungailiat',
                    'short_name' => 'Penduduk Sungailiat',
                    'value' => 95866,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.18,
                    'trend' => [
                        ['year' => 2024, 'value' => 95866],
                        ['year' => 2023, 'value' => 94750],
                        ['year' => 2022, 'value' => 93600],
                        ['year' => 2021, 'value' => 92480],
                        ['year' => 2020, 'value' => 91390],
                    ],
                ],
                [
                    'id' => 'density_sungailiat',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 664,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.22,
                    'trend' => [
                        ['year' => 2024, 'value' => 664],
                        ['year' => 2023, 'value' => 656],
                        ['year' => 2022, 'value' => 648],
                        ['year' => 2021, 'value' => 640],
                        ['year' => 2020, 'value' => 633],
                    ],
                ],
                [
                    'id' => 'area_sungailiat',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 144.38,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 144.38],
                        ['year' => 2023, 'value' => 144.38],
                        ['year' => 2022, 'value' => 144.38],
                        ['year' => 2021, 'value' => 144.38],
                        ['year' => 2020, 'value' => 144.38],
                    ],
                ],
                [
                    'id' => 'pdrb_sungailiat',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 76.50,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.52,
                    'trend' => [
                        ['year' => 2024, 'value' => 76.50],
                        ['year' => 2023, 'value' => 72.50],
                        ['year' => 2022, 'value' => 69.20],
                        ['year' => 2021, 'value' => 65.40],
                        ['year' => 2020, 'value' => 61.20],
                    ],
                ],
            ],
            // Data Sektoral Spesifik Kecamatan
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 95866],
                    ['year' => 2023, 'value' => 94750],
                    ['year' => 2022, 'value' => 93600],
                    ['year' => 2021, 'value' => 92480],
                    ['year' => 2020, 'value' => 91390],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 76.50],
                    ['year' => 2023, 'value' => 72.50],
                    ['year' => 2022, 'value' => 69.20],
                    ['year' => 2021, 'value' => 65.40],
                    ['year' => 2020, 'value' => 61.20],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 48200],
                    ['year' => 2023, 'value' => 47400],
                    ['year' => 2022, 'value' => 46600],
                    ['year' => 2021, 'value' => 45800],
                    ['year' => 2020, 'value' => 45000],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 18],
                    ['year' => 2023, 'value' => 17],
                    ['year' => 2022, 'value' => 17],
                    ['year' => 2021, 'value' => 16],
                    ['year' => 2020, 'value' => 15],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 64],
                    ['year' => 2023, 'value' => 64],
                    ['year' => 2022, 'value' => 63],
                    ['year' => 2021, 'value' => 62],
                    ['year' => 2020, 'value' => 61],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 2450],
                    ['year' => 2023, 'value' => 2400],
                    ['year' => 2022, 'value' => 2360],
                    ['year' => 2021, 'value' => 2310],
                    ['year' => 2020, 'value' => 2250],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 6820],
                    ['year' => 2023, 'value' => 6950],
                    ['year' => 2022, 'value' => 7120],
                    ['year' => 2021, 'value' => 7350],
                    ['year' => 2020, 'value' => 7580],
                ],
            ],
        ],
        [
            'id' => 'belinyu',
            'name' => 'Belinyu',
            'capital' => 'Belinyu',
            'area_km2' => 545.92,
            'population' => 52140,
            'density' => 96,
            'pdrb_kapita' => 68.20,
            'angkatan_kerja' => 26400,
            'puskesmas_faskes' => 12,
            'sekolah_total' => 45,
            'lahan_tani' => 6800,
            'penerima_bansos' => 4950,
            'kpi_cards' => [
                [
                    'id' => 'pop_belinyu',
                    'name' => 'Jumlah Penduduk Belinyu',
                    'short_name' => 'Penduduk Belinyu',
                    'value' => 52140,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.05,
                    'trend' => [
                        ['year' => 2024, 'value' => 52140],
                        ['year' => 2023, 'value' => 51600],
                        ['year' => 2022, 'value' => 51050],
                        ['year' => 2021, 'value' => 50520],
                        ['year' => 2020, 'value' => 50010],
                    ],
                ],
                [
                    'id' => 'density_belinyu',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 96,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.05,
                    'trend' => [
                        ['year' => 2024, 'value' => 96],
                        ['year' => 2023, 'value' => 95],
                        ['year' => 2022, 'value' => 93],
                        ['year' => 2021, 'value' => 92],
                        ['year' => 2020, 'value' => 91],
                    ],
                ],
                [
                    'id' => 'area_belinyu',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 545.92,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 545.92],
                        ['year' => 2023, 'value' => 545.92],
                        ['year' => 2022, 'value' => 545.92],
                        ['year' => 2021, 'value' => 545.92],
                        ['year' => 2020, 'value' => 545.92],
                    ],
                ],
                [
                    'id' => 'pdrb_belinyu',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 68.20,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.25,
                    'trend' => [
                        ['year' => 2024, 'value' => 68.20],
                        ['year' => 2023, 'value' => 64.80],
                        ['year' => 2022, 'value' => 61.90],
                        ['year' => 2021, 'value' => 58.60],
                        ['year' => 2020, 'value' => 54.80],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 52140],
                    ['year' => 2023, 'value' => 51600],
                    ['year' => 2022, 'value' => 51050],
                    ['year' => 2021, 'value' => 50520],
                    ['year' => 2020, 'value' => 50010],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 68.20],
                    ['year' => 2023, 'value' => 64.80],
                    ['year' => 2022, 'value' => 61.90],
                    ['year' => 2021, 'value' => 58.60],
                    ['year' => 2020, 'value' => 54.80],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 26400],
                    ['year' => 2023, 'value' => 26050],
                    ['year' => 2022, 'value' => 25700],
                    ['year' => 2021, 'value' => 25300],
                    ['year' => 2020, 'value' => 24900],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 12],
                    ['year' => 2023, 'value' => 12],
                    ['year' => 2022, 'value' => 11],
                    ['year' => 2021, 'value' => 11],
                    ['year' => 2020, 'value' => 10],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 45],
                    ['year' => 2023, 'value' => 45],
                    ['year' => 2022, 'value' => 44],
                    ['year' => 2021, 'value' => 43],
                    ['year' => 2020, 'value' => 42],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 6800],
                    ['year' => 2023, 'value' => 6650],
                    ['year' => 2022, 'value' => 6520],
                    ['year' => 2021, 'value' => 6380],
                    ['year' => 2020, 'value' => 6210],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 4950],
                    ['year' => 2023, 'value' => 5080],
                    ['year' => 2022, 'value' => 5210],
                    ['year' => 2021, 'value' => 5380],
                    ['year' => 2020, 'value' => 5540],
                ],
            ],
        ],
        [
            'id' => 'mendo-barat',
            'name' => 'Mendo Barat',
            'capital' => 'Petaling',
            'area_km2' => 574.44,
            'population' => 51920,
            'density' => 90,
            'pdrb_kapita' => 58.40,
            'angkatan_kerja' => 25800,
            'puskesmas_faskes' => 10,
            'sekolah_total' => 38,
            'lahan_tani' => 9400,
            'penerima_bansos' => 4890,
            'kpi_cards' => [
                [
                    'id' => 'pop_mendo',
                    'name' => 'Jumlah Penduduk Mendo Barat',
                    'short_name' => 'Penduduk Mendo Barat',
                    'value' => 51920,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.20,
                    'trend' => [
                        ['year' => 2024, 'value' => 51920],
                        ['year' => 2023, 'value' => 51300],
                        ['year' => 2022, 'value' => 50700],
                        ['year' => 2021, 'value' => 50100],
                        ['year' => 2020, 'value' => 49500],
                    ],
                ],
                [
                    'id' => 'density_mendo',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 90,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.12,
                    'trend' => [
                        ['year' => 2024, 'value' => 90],
                        ['year' => 2023, 'value' => 89],
                        ['year' => 2022, 'value' => 88],
                        ['year' => 2021, 'value' => 87],
                        ['year' => 2020, 'value' => 86],
                    ],
                ],
                [
                    'id' => 'area_mendo',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 574.44,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 574.44],
                        ['year' => 2023, 'value' => 574.44],
                        ['year' => 2022, 'value' => 574.44],
                        ['year' => 2021, 'value' => 574.44],
                        ['year' => 2020, 'value' => 574.44],
                    ],
                ],
                [
                    'id' => 'tani_mendo',
                    'name' => 'Luas Panen Pertanian/Kebun',
                    'short_name' => 'Lahan Pertanian',
                    'value' => 9400,
                    'unit' => 'Hektar',
                    'yoy_change' => 3.45,
                    'trend' => [
                        ['year' => 2024, 'value' => 9400],
                        ['year' => 2023, 'value' => 9080],
                        ['year' => 2022, 'value' => 8790],
                        ['year' => 2021, 'value' => 8520],
                        ['year' => 2020, 'value' => 8250],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 51920],
                    ['year' => 2023, 'value' => 51300],
                    ['year' => 2022, 'value' => 50700],
                    ['year' => 2021, 'value' => 50100],
                    ['year' => 2020, 'value' => 49500],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 58.40],
                    ['year' => 2023, 'value' => 55.60],
                    ['year' => 2022, 'value' => 53.10],
                    ['year' => 2021, 'value' => 50.40],
                    ['year' => 2020, 'value' => 47.20],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 25800],
                    ['year' => 2023, 'value' => 25400],
                    ['year' => 2022, 'value' => 25000],
                    ['year' => 2021, 'value' => 24600],
                    ['year' => 2020, 'value' => 24200],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 10],
                    ['year' => 2023, 'value' => 10],
                    ['year' => 2022, 'value' => 9],
                    ['year' => 2021, 'value' => 9],
                    ['year' => 2020, 'value' => 8],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 38],
                    ['year' => 2023, 'value' => 38],
                    ['year' => 2022, 'value' => 37],
                    ['year' => 2021, 'value' => 36],
                    ['year' => 2020, 'value' => 35],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 9400],
                    ['year' => 2023, 'value' => 9080],
                    ['year' => 2022, 'value' => 8790],
                    ['year' => 2021, 'value' => 8520],
                    ['year' => 2020, 'value' => 8250],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 4890],
                    ['year' => 2023, 'value' => 5010],
                    ['year' => 2022, 'value' => 5160],
                    ['year' => 2021, 'value' => 5340],
                    ['year' => 2020, 'value' => 5510],
                ],
            ],
        ],
        [
            'id' => 'pemali',
            'name' => 'Pemali',
            'capital' => 'Air Duren',
            'area_km2' => 128.53,
            'population' => 35790,
            'density' => 278,
            'pdrb_kapita' => 66.10,
            'angkatan_kerja' => 17900,
            'puskesmas_faskes' => 8,
            'sekolah_total' => 28,
            'lahan_tani' => 3850,
            'penerima_bansos' => 3420,
            'kpi_cards' => [
                [
                    'id' => 'pop_pemali',
                    'name' => 'Jumlah Penduduk Pemali',
                    'short_name' => 'Penduduk Pemali',
                    'value' => 35790,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.10,
                    'trend' => [
                        ['year' => 2024, 'value' => 35790],
                        ['year' => 2023, 'value' => 35400],
                        ['year' => 2022, 'value' => 35000],
                        ['year' => 2021, 'value' => 34600],
                        ['year' => 2020, 'value' => 34200],
                    ],
                ],
                [
                    'id' => 'density_pemali',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 278,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.09,
                    'trend' => [
                        ['year' => 2024, 'value' => 278],
                        ['year' => 2023, 'value' => 275],
                        ['year' => 2022, 'value' => 272],
                        ['year' => 2021, 'value' => 269],
                        ['year' => 2020, 'value' => 266],
                    ],
                ],
                [
                    'id' => 'area_pemali',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 128.53,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 128.53],
                        ['year' => 2023, 'value' => 128.53],
                        ['year' => 2022, 'value' => 128.53],
                        ['year' => 2021, 'value' => 128.53],
                        ['year' => 2020, 'value' => 128.53],
                    ],
                ],
                [
                    'id' => 'pdrb_pemali',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 66.10,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.15,
                    'trend' => [
                        ['year' => 2024, 'value' => 66.10],
                        ['year' => 2023, 'value' => 62.80],
                        ['year' => 2022, 'value' => 59.90],
                        ['year' => 2021, 'value' => 56.70],
                        ['year' => 2020, 'value' => 53.10],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 35790],
                    ['year' => 2023, 'value' => 35400],
                    ['year' => 2022, 'value' => 35000],
                    ['year' => 2021, 'value' => 34600],
                    ['year' => 2020, 'value' => 34200],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 66.10],
                    ['year' => 2023, 'value' => 62.80],
                    ['year' => 2022, 'value' => 59.90],
                    ['year' => 2021, 'value' => 56.70],
                    ['year' => 2020, 'value' => 53.10],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 17900],
                    ['year' => 2023, 'value' => 17650],
                    ['year' => 2022, 'value' => 17400],
                    ['year' => 2021, 'value' => 17150],
                    ['year' => 2020, 'value' => 16900],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 8],
                    ['year' => 2023, 'value' => 8],
                    ['year' => 2022, 'value' => 7],
                    ['year' => 2021, 'value' => 7],
                    ['year' => 2020, 'value' => 6],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 28],
                    ['year' => 2023, 'value' => 28],
                    ['year' => 2022, 'value' => 27],
                    ['year' => 2021, 'value' => 26],
                    ['year' => 2020, 'value' => 25],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 3850],
                    ['year' => 2023, 'value' => 3740],
                    ['year' => 2022, 'value' => 3650],
                    ['year' => 2021, 'value' => 3550],
                    ['year' => 2020, 'value' => 3450],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 3420],
                    ['year' => 2023, 'value' => 3510],
                    ['year' => 2022, 'value' => 3620],
                    ['year' => 2021, 'value' => 3750],
                    ['year' => 2020, 'value' => 3880],
                ],
            ],
        ],
        [
            'id' => 'merawang',
            'name' => 'Merawang',
            'capital' => 'Baturusa',
            'area_km2' => 204.93,
            'population' => 32480,
            'density' => 159,
            'pdrb_kapita' => 65.80,
            'angkatan_kerja' => 16200,
            'puskesmas_faskes' => 9,
            'sekolah_total' => 29,
            'lahan_tani' => 4200,
            'penerima_bansos' => 3180,
            'kpi_cards' => [
                [
                    'id' => 'pop_merawang',
                    'name' => 'Jumlah Penduduk Merawang',
                    'short_name' => 'Penduduk Merawang',
                    'value' => 32480,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.15,
                    'trend' => [
                        ['year' => 2024, 'value' => 32480],
                        ['year' => 2023, 'value' => 32110],
                        ['year' => 2022, 'value' => 31750],
                        ['year' => 2021, 'value' => 31390],
                        ['year' => 2020, 'value' => 31020],
                    ],
                ],
                [
                    'id' => 'density_merawang',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 159,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.27,
                    'trend' => [
                        ['year' => 2024, 'value' => 159],
                        ['year' => 2023, 'value' => 157],
                        ['year' => 2022, 'value' => 155],
                        ['year' => 2021, 'value' => 153],
                        ['year' => 2020, 'value' => 151],
                    ],
                ],
                [
                    'id' => 'area_merawang',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 204.93,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 204.93],
                        ['year' => 2023, 'value' => 204.93],
                        ['year' => 2022, 'value' => 204.93],
                        ['year' => 2021, 'value' => 204.93],
                        ['year' => 2020, 'value' => 204.93],
                    ],
                ],
                [
                    'id' => 'pdrb_merawang',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 65.80,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.28,
                    'trend' => [
                        ['year' => 2024, 'value' => 65.80],
                        ['year' => 2023, 'value' => 62.50],
                        ['year' => 2022, 'value' => 59.60],
                        ['year' => 2021, 'value' => 56.40],
                        ['year' => 2020, 'value' => 52.80],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 32480],
                    ['year' => 2023, 'value' => 32110],
                    ['year' => 2022, 'value' => 31750],
                    ['year' => 2021, 'value' => 31390],
                    ['year' => 2020, 'value' => 31020],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 65.80],
                    ['year' => 2023, 'value' => 62.50],
                    ['year' => 2022, 'value' => 59.60],
                    ['year' => 2021, 'value' => 56.40],
                    ['year' => 2020, 'value' => 52.80],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 16200],
                    ['year' => 2023, 'value' => 15980],
                    ['year' => 2022, 'value' => 15760],
                    ['year' => 2021, 'value' => 15540],
                    ['year' => 2020, 'value' => 15300],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 9],
                    ['year' => 2023, 'value' => 9],
                    ['year' => 2022, 'value' => 8],
                    ['year' => 2021, 'value' => 8],
                    ['year' => 2020, 'value' => 7],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 29],
                    ['year' => 2023, 'value' => 29],
                    ['year' => 2022, 'value' => 28],
                    ['year' => 2021, 'value' => 27],
                    ['year' => 2020, 'value' => 26],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 4200],
                    ['year' => 2023, 'value' => 4080],
                    ['year' => 2022, 'value' => 3970],
                    ['year' => 2021, 'value' => 3860],
                    ['year' => 2020, 'value' => 3750],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 3180],
                    ['year' => 2023, 'value' => 3270],
                    ['year' => 2022, 'value' => 3380],
                    ['year' => 2021, 'value' => 3500],
                    ['year' => 2020, 'value' => 3620],
                ],
            ],
        ],
        [
            'id' => 'riau-silip',
            'name' => 'Riau Silip',
            'capital' => 'Riau',
            'area_km2' => 521.80,
            'population' => 29610,
            'density' => 57,
            'pdrb_kapita' => 59.20,
            'angkatan_kerja' => 14800,
            'puskesmas_faskes' => 7,
            'sekolah_total' => 26,
            'lahan_tani' => 7600,
            'penerima_bansos' => 2980,
            'kpi_cards' => [
                [
                    'id' => 'pop_riau',
                    'name' => 'Jumlah Penduduk Riau Silip',
                    'short_name' => 'Penduduk Riau Silip',
                    'value' => 29610,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.06,
                    'trend' => [
                        ['year' => 2024, 'value' => 29610],
                        ['year' => 2023, 'value' => 29300],
                        ['year' => 2022, 'value' => 28990],
                        ['year' => 2021, 'value' => 28680],
                        ['year' => 2020, 'value' => 28380],
                    ],
                ],
                [
                    'id' => 'density_riau',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 57,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.78,
                    'trend' => [
                        ['year' => 2024, 'value' => 57],
                        ['year' => 2023, 'value' => 56],
                        ['year' => 2022, 'value' => 55],
                        ['year' => 2021, 'value' => 55],
                        ['year' => 2020, 'value' => 54],
                    ],
                ],
                [
                    'id' => 'area_riau',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 521.80,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 521.80],
                        ['year' => 2023, 'value' => 521.80],
                        ['year' => 2022, 'value' => 521.80],
                        ['year' => 2021, 'value' => 521.80],
                        ['year' => 2020, 'value' => 521.80],
                    ],
                ],
                [
                    'id' => 'pdrb_riau',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 59.20,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.15,
                    'trend' => [
                        ['year' => 2024, 'value' => 59.20],
                        ['year' => 2023, 'value' => 56.30],
                        ['year' => 2022, 'value' => 53.70],
                        ['year' => 2021, 'value' => 50.80],
                        ['year' => 2020, 'value' => 47.60],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 29610],
                    ['year' => 2023, 'value' => 29300],
                    ['year' => 2022, 'value' => 28990],
                    ['year' => 2021, 'value' => 28680],
                    ['year' => 2020, 'value' => 28380],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 59.20],
                    ['year' => 2023, 'value' => 56.30],
                    ['year' => 2022, 'value' => 53.70],
                    ['year' => 2021, 'value' => 50.80],
                    ['year' => 2020, 'value' => 47.60],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 14800],
                    ['year' => 2023, 'value' => 14600],
                    ['year' => 2022, 'value' => 14400],
                    ['year' => 2021, 'value' => 14200],
                    ['year' => 2020, 'value' => 14000],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 7],
                    ['year' => 2023, 'value' => 7],
                    ['year' => 2022, 'value' => 6],
                    ['year' => 2021, 'value' => 6],
                    ['year' => 2020, 'value' => 5],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 26],
                    ['year' => 2023, 'value' => 26],
                    ['year' => 2022, 'value' => 25],
                    ['year' => 2021, 'value' => 24],
                    ['year' => 2020, 'value' => 23],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 7600],
                    ['year' => 2023, 'value' => 7380],
                    ['year' => 2022, 'value' => 7180],
                    ['year' => 2021, 'value' => 6980],
                    ['year' => 2020, 'value' => 6750],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 2980],
                    ['year' => 2023, 'value' => 3060],
                    ['year' => 2022, 'value' => 3160],
                    ['year' => 2021, 'value' => 3280],
                    ['year' => 2020, 'value' => 3390],
                ],
            ],
        ],
        [
            'id' => 'puding-besar',
            'name' => 'Puding Besar',
            'capital' => 'Puding',
            'area_km2' => 373.10,
            'population' => 24792,
            'density' => 66,
            'pdrb_kapita' => 57.10,
            'angkatan_kerja' => 12400,
            'puskesmas_faskes' => 6,
            'sekolah_total' => 22,
            'lahan_tani' => 6100,
            'penerima_bansos' => 2610,
            'kpi_cards' => [
                [
                    'id' => 'pop_puding',
                    'name' => 'Jumlah Penduduk Puding Besar',
                    'short_name' => 'Penduduk Puding Besar',
                    'value' => 24792,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.08,
                    'trend' => [
                        ['year' => 2024, 'value' => 24792],
                        ['year' => 2023, 'value' => 24520],
                        ['year' => 2022, 'value' => 24260],
                        ['year' => 2021, 'value' => 24000],
                        ['year' => 2020, 'value' => 23750],
                    ],
                ],
                [
                    'id' => 'density_puding',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 66,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 1.53,
                    'trend' => [
                        ['year' => 2024, 'value' => 66],
                        ['year' => 2023, 'value' => 65],
                        ['year' => 2022, 'value' => 65],
                        ['year' => 2021, 'value' => 64],
                        ['year' => 2020, 'value' => 63],
                    ],
                ],
                [
                    'id' => 'area_puding',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 373.10,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 373.10],
                        ['year' => 2023, 'value' => 373.10],
                        ['year' => 2022, 'value' => 373.10],
                        ['year' => 2021, 'value' => 373.10],
                        ['year' => 2020, 'value' => 373.10],
                    ],
                ],
                [
                    'id' => 'pdrb_puding',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 57.10,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.15,
                    'trend' => [
                        ['year' => 2024, 'value' => 57.10],
                        ['year' => 2023, 'value' => 54.30],
                        ['year' => 2022, 'value' => 51.80],
                        ['year' => 2021, 'value' => 49.00],
                        ['year' => 2020, 'value' => 45.90],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 24792],
                    ['year' => 2023, 'value' => 24520],
                    ['year' => 2022, 'value' => 24260],
                    ['year' => 2021, 'value' => 24000],
                    ['year' => 2020, 'value' => 23750],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 57.10],
                    ['year' => 2023, 'value' => 54.30],
                    ['year' => 2022, 'value' => 51.80],
                    ['year' => 2021, 'value' => 49.00],
                    ['year' => 2020, 'value' => 45.90],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 12400],
                    ['year' => 2023, 'value' => 12220],
                    ['year' => 2022, 'value' => 12050],
                    ['year' => 2021, 'value' => 11880],
                    ['year' => 2020, 'value' => 11700],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 6],
                    ['year' => 2023, 'value' => 6],
                    ['year' => 2022, 'value' => 5],
                    ['year' => 2021, 'value' => 5],
                    ['year' => 2020, 'value' => 4],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 22],
                    ['year' => 2023, 'value' => 22],
                    ['year' => 2022, 'value' => 21],
                    ['year' => 2021, 'value' => 20],
                    ['year' => 2020, 'value' => 19],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 6100],
                    ['year' => 2023, 'value' => 5920],
                    ['year' => 2022, 'value' => 5750],
                    ['year' => 2021, 'value' => 5580],
                    ['year' => 2020, 'value' => 5400],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 2610],
                    ['year' => 2023, 'value' => 2680],
                    ['year' => 2022, 'value' => 2760],
                    ['year' => 2021, 'value' => 2850],
                    ['year' => 2020, 'value' => 2940],
                ],
            ],
        ],
        [
            'id' => 'bakam',
            'name' => 'Bakam',
            'capital' => 'Bakam',
            'area_km2' => 482.90,
            'population' => 19460,
            'density' => 40,
            'pdrb_kapita' => 55.60,
            'angkatan_kerja' => 9800,
            'puskesmas_faskes' => 5,
            'sekolah_total' => 18,
            'lahan_tani' => 5900,
            'penerima_bansos' => 2400,
            'kpi_cards' => [
                [
                    'id' => 'pop_bakam',
                    'name' => 'Jumlah Penduduk Bakam',
                    'short_name' => 'Penduduk Bakam',
                    'value' => 19460,
                    'unit' => 'Jiwa',
                    'yoy_change' => 1.03,
                    'trend' => [
                        ['year' => 2024, 'value' => 19460],
                        ['year' => 2023, 'value' => 19260],
                        ['year' => 2022, 'value' => 19060],
                        ['year' => 2021, 'value' => 18860],
                        ['year' => 2020, 'value' => 18670],
                    ],
                ],
                [
                    'id' => 'density_bakam',
                    'name' => 'Kepadatan Penduduk',
                    'short_name' => 'Kepadatan Wilayah',
                    'value' => 40,
                    'unit' => 'Jiwa/Km²',
                    'yoy_change' => 2.56,
                    'trend' => [
                        ['year' => 2024, 'value' => 40],
                        ['year' => 2023, 'value' => 39],
                        ['year' => 2022, 'value' => 39],
                        ['year' => 2021, 'value' => 39],
                        ['year' => 2020, 'value' => 38],
                    ],
                ],
                [
                    'id' => 'area_bakam',
                    'name' => 'Luas Wilayah Kecamatan',
                    'short_name' => 'Luas Wilayah',
                    'value' => 482.90,
                    'unit' => 'Km²',
                    'yoy_change' => 0.0,
                    'trend' => [
                        ['year' => 2024, 'value' => 482.90],
                        ['year' => 2023, 'value' => 482.90],
                        ['year' => 2022, 'value' => 482.90],
                        ['year' => 2021, 'value' => 482.90],
                        ['year' => 2020, 'value' => 482.90],
                    ],
                ],
                [
                    'id' => 'pdrb_bakam',
                    'name' => 'Estimasi PDRB per Kapita',
                    'short_name' => 'PDRB per Kapita',
                    'value' => 55.60,
                    'unit' => 'Juta Rp',
                    'yoy_change' => 5.10,
                    'trend' => [
                        ['year' => 2024, 'value' => 55.60],
                        ['year' => 2023, 'value' => 52.90],
                        ['year' => 2022, 'value' => 50.40],
                        ['year' => 2021, 'value' => 47.80],
                        ['year' => 2020, 'value' => 44.90],
                    ],
                ],
            ],
            'sector_trends' => [
                'kependudukan' => [
                    ['year' => 2024, 'value' => 19460],
                    ['year' => 2023, 'value' => 19260],
                    ['year' => 2022, 'value' => 19060],
                    ['year' => 2021, 'value' => 18860],
                    ['year' => 2020, 'value' => 18670],
                ],
                'perekonomian' => [
                    ['year' => 2024, 'value' => 55.60],
                    ['year' => 2023, 'value' => 52.90],
                    ['year' => 2022, 'value' => 50.40],
                    ['year' => 2021, 'value' => 47.80],
                    ['year' => 2020, 'value' => 44.90],
                ],
                'ketenagakerjaan' => [
                    ['year' => 2024, 'value' => 9800],
                    ['year' => 2023, 'value' => 9650],
                    ['year' => 2022, 'value' => 9500],
                    ['year' => 2021, 'value' => 9350],
                    ['year' => 2020, 'value' => 9200],
                ],
                'kesehatan' => [
                    ['year' => 2024, 'value' => 5],
                    ['year' => 2023, 'value' => 5],
                    ['year' => 2022, 'value' => 4],
                    ['year' => 2021, 'value' => 4],
                    ['year' => 2020, 'value' => 3],
                ],
                'pendidikan' => [
                    ['year' => 2024, 'value' => 18],
                    ['year' => 2023, 'value' => 18],
                    ['year' => 2022, 'value' => 17],
                    ['year' => 2021, 'value' => 16],
                    ['year' => 2020, 'value' => 15],
                ],
                'pertanian' => [
                    ['year' => 2024, 'value' => 5900],
                    ['year' => 2023, 'value' => 5720],
                    ['year' => 2022, 'value' => 5560],
                    ['year' => 2021, 'value' => 5390],
                    ['year' => 2020, 'value' => 5210],
                ],
                'sosial' => [
                    ['year' => 2024, 'value' => 2400],
                    ['year' => 2023, 'value' => 2470],
                    ['year' => 2022, 'value' => 2550],
                    ['year' => 2021, 'value' => 2630],
                    ['year' => 2020, 'value' => 2720],
                ],
            ],
        ],
    ],

    // Dataset Rujukan Terkait (Katalog SDI Bangka)
    'featured_datasets' => [
        [
            'id' => 'ds-01',
            'title' => 'Statistik Kependudukan & Proyeksi Penduduk per Kecamatan Kab. Bangka 2020–2024',
            'category' => 'Kependudukan',
            'opd' => 'Dinas Kependudukan dan Pencatatan Sipil Kab. Bangka',
            'updated_at' => '15 Januari 2025',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
        [
            'id' => 'ds-02',
            'title' => 'Indikator PDRB & Pertumbuhan Ekonomi Lapangan Usaha Kab. Bangka 2020–2024',
            'category' => 'Perekonomian',
            'opd' => 'Badan Pusat Statistik (BPS) & Bappeda Kab. Bangka',
            'updated_at' => '02 Februari 2025',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
        [
            'id' => 'ds-03',
            'title' => 'Capaian Indeks Pembangunan Manusia (IPM) & Dimensi Pembentuk Kab. Bangka 2024',
            'category' => 'Pendidikan & Kesehatan',
            'opd' => 'Bappeda Kabupaten Bangka',
            'updated_at' => '10 Desember 2024',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
    ],
];
