<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Data Statistik Dasar Resmi Kabupaten Bangka (Sumber: BPS Kabupaten Bangka)
    |--------------------------------------------------------------------------
    | Portal: https://satudata.bangka.go.id/statistik-dasar
    | Sumber Rujukan Resmi: Badan Pusat Statistik (BPS) Kabupaten Bangka
    | Publikasi: Kabupaten Bangka Dalam Angka 2024 & Berita Resmi Statistik BPS
    */

    'years' => [2020, 2021, 2022, 2023, 2024],
    'default_year' => 2024,

    // 4 Indikator Makro Utama (Headline Indicators BPS)
    'headline_indicators' => [
        [
            'id' => 'ipm',
            'name' => 'Indeks Pembangunan Manusia (IPM)',
            'short_name' => 'IPM Bangka',
            'sector' => 'pendidikan',
            'value' => 74.66,
            'unit' => 'Poin',
            'yoy_change' => 0.43,
            'lower_is_better' => false,
            'trend' => [
                ['year' => 2020, 'value' => 72.40],
                ['year' => 2021, 'value' => 72.85],
                ['year' => 2022, 'value' => 73.48],
                ['year' => 2023, 'value' => 74.23],
                ['year' => 2024, 'value' => 74.66],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Indeks komposit yang mengukur capaian pembangunan manusia berbasis tiga dimensi dasar: umur panjang dan hidup sehat, pengetahuan, serta standar hidup layak.',
                'satuan' => 'Poin Indeks (0-100)',
                'metodologi' => 'Metode baru BPS dengan agregasi rata-rata geometrik UHH, HLS, RLS, dan Pengeluaran Riil per Kapita disesuaikan.',
                'jadwal_rilis' => 'Tahunan (November/Desember)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'kemiskinan',
            'name' => 'Persentase Penduduk Miskin',
            'short_name' => 'Kemiskinan',
            'sector' => 'perekonomian',
            'value' => 4.55,
            'unit' => '%',
            'yoy_change' => -0.25,
            'lower_is_better' => true,
            'trend' => [
                ['year' => 2020, 'value' => 5.36],
                ['year' => 2021, 'value' => 5.12],
                ['year' => 2022, 'value' => 4.91],
                ['year' => 2023, 'value' => 4.80],
                ['year' => 2024, 'value' => 4.55],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Bappeda Kab. Bangka',
                'definisi' => 'Persentase penduduk dengan pengeluaran per kapita per bulan di bawah Garis Kemiskinan (GK) Kabupaten Bangka.',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Sosial Ekonomi Nasional (Susenas) Modul Konsumsi/Pengeluaran periode Maret.',
                'jadwal_rilis' => 'Tahunan (Juli/Agustus)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'pertumbuhan-ekonomi',
            'name' => 'Laju Pertumbuhan Ekonomi (PDRB ADHK)',
            'short_name' => 'Pertumbuhan Ekonomi',
            'sector' => 'perekonomian',
            'value' => 4.38,
            'unit' => '%',
            'yoy_change' => 0.35,
            'lower_is_better' => false,
            'trend' => [
                ['year' => 2020, 'value' => -2.30],
                ['year' => 2021, 'value' => 4.25],
                ['year' => 2022, 'value' => 4.03],
                ['year' => 2023, 'value' => 4.38],
                ['year' => 2024, 'value' => 4.15],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Pertumbuhan Produk Domestik Regional Bruto (PDRB) atas dasar harga konstan 2010 yang mencerminkan pertumbuhan output riil barang dan jasa di Kab. Bangka.',
                'satuan' => 'Persen (%) per Tahun',
                'metodologi' => 'Penghitungan PDRB 17 Lapangan Usaha dan 6 Pengeluaran berdasarkan SNA 2008.',
                'jadwal_rilis' => 'Tahunan (Februari/Maret)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
        [
            'id' => 'tpt',
            'name' => 'Tingkat Pengangguran Terbuka (TPT)',
            'short_name' => 'TPT (Pengangguran)',
            'sector' => 'ketenagakerjaan',
            'value' => 5.03,
            'unit' => '%',
            'yoy_change' => -0.36,
            'lower_is_better' => true,
            'trend' => [
                ['year' => 2020, 'value' => 5.82],
                ['year' => 2021, 'value' => 5.56],
                ['year' => 2022, 'value' => 5.39],
                ['year' => 2023, 'value' => 5.03],
                ['year' => 2024, 'value' => 4.88],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinakerperindag Kab. Bangka',
                'definisi' => 'Persentase jumlah penganggur terhadap jumlah total angkatan kerja di Kabupaten Bangka.',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Angkatan Kerja Nasional (Sakernas) periode Agustus.',
                'jadwal_rilis' => 'Tahunan (November)',
                'sumber_url' => 'https://bangkakab.bps.go.id',
            ],
        ],
    ],

    // 7 Sektor Urusan Pemerintahan
    'sectors' => [
        ['id' => 'kependudukan', 'label' => 'Kependudukan', 'icon' => 'users', 'color' => '#DC2626'],
        ['id' => 'perekonomian', 'label' => 'Perekonomian', 'icon' => 'trending-up', 'color' => '#E11D48'],
        ['id' => 'ketenagakerjaan', 'label' => 'Ketenagakerjaan', 'icon' => 'briefcase', 'color' => '#BE123C'],
        ['id' => 'kesehatan', 'label' => 'Kesehatan', 'icon' => 'heart-pulse', 'color' => '#991B1B'],
        ['id' => 'pendidikan', 'label' => 'Pendidikan', 'icon' => 'graduation-cap', 'color' => '#B91C1C'],
        ['id' => 'pertanian', 'label' => 'Pertanian & Pangan', 'icon' => 'wheat', 'color' => '#C2410C'],
        ['id' => 'sosial', 'label' => 'Sosial & Kesejahteraan', 'icon' => 'shield-check', 'color' => '#7C2D12'],
    ],

    // Indikator Utama per Sektor
    'sector_indicators' => [
        'kependudukan' => [
            'name' => 'Jumlah Penduduk Kabupaten Bangka',
            'short_name' => 'Total Penduduk',
            'unit' => 'Jiwa',
            'value' => 342058,
            'yoy_change' => 1.15,
            'trend' => [
                ['year' => 2020, 'value' => 326265],
                ['year' => 2021, 'value' => 330142],
                ['year' => 2022, 'value' => 334220],
                ['year' => 2023, 'value' => 338175],
                ['year' => 2024, 'value' => 342058],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinas Dukcapil Kab. Bangka',
                'definisi' => 'Jumlah keseluruhan warga negara dan penduduk yang berdomisili resmi di wilayah Kabupaten Bangka.',
                'satuan' => 'Orang / Jiwa',
                'metodologi' => 'Sensus Penduduk & Proyeksi Penduduk Interim BPS - Ditjen Dukcapil.',
                'jadwal_rilis' => 'Tahunan (Semester II)',
            ],
            'column' => [
                'key' => 'population',
                'label' => 'Jumlah Penduduk',
                'unit' => 'Jiwa',
                'digits' => 0,
            ],
        ],
        'perekonomian' => [
            'name' => 'PDRB per Kapita Atas Dasar Harga Berlaku',
            'short_name' => 'PDRB per Kapita',
            'unit' => 'Juta Rp',
            'value' => 64.82,
            'yoy_change' => 5.42,
            'trend' => [
                ['year' => 2020, 'value' => 52.30],
                ['year' => 2021, 'value' => 56.15],
                ['year' => 2022, 'value' => 59.80],
                ['year' => 2023, 'value' => 62.40],
                ['year' => 2024, 'value' => 64.82],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Nilai PDRB ADHB dibagi dengan jumlah penduduk pertengahan tahun yang mencerminkan pendapatan rata-rata per kapita.',
                'satuan' => 'Juta Rupiah / Tahun',
                'metodologi' => 'Perhitungan PDRB Berdasarkan Sistem Neraca Nasional 2008.',
                'jadwal_rilis' => 'Tahunan (Maret)',
            ],
            'column' => [
                'key' => 'pdrb_kapita',
                'label' => 'Estimasi PDRB per Kapita',
                'unit' => 'Juta Rp',
                'digits' => 2,
            ],
        ],
        'ketenagakerjaan' => [
            'name' => 'Tingkat Partisipasi Angkatan Kerja (TPAK)',
            'short_name' => 'TPAK Bangka',
            'unit' => '%',
            'value' => 67.85,
            'yoy_change' => 0.62,
            'trend' => [
                ['year' => 2020, 'value' => 65.40],
                ['year' => 2021, 'value' => 66.12],
                ['year' => 2022, 'value' => 66.90],
                ['year' => 2023, 'value' => 67.23],
                ['year' => 2024, 'value' => 67.85],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka',
                'definisi' => 'Persentase jumlah angkatan kerja (bekerja + menganggur) terhadap penduduk usia kerja (15 tahun ke atas).',
                'satuan' => 'Persen (%)',
                'metodologi' => 'Survei Angkatan Kerja Nasional (Sakernas) BPS.',
                'jadwal_rilis' => 'Tahunan (November)',
            ],
            'column' => [
                'key' => 'angkatan_kerja',
                'label' => 'Angkatan Kerja Aktif',
                'unit' => 'Jiwa',
                'digits' => 0,
            ],
        ],
        'kesehatan' => [
            'name' => 'Angka Harapan Hidup saat Lahir (UHH)',
            'short_name' => 'Usia Harapan Hidup',
            'unit' => 'Tahun',
            'value' => 73.15,
            'yoy_change' => 0.28,
            'trend' => [
                ['year' => 2020, 'value' => 71.95],
                ['year' => 2021, 'value' => 72.30],
                ['year' => 2022, 'value' => 72.65],
                ['year' => 2023, 'value' => 72.87],
                ['year' => 2024, 'value' => 73.15],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dinas Kesehatan Kab. Bangka',
                'definisi' => 'Rata-rata perkiraan banyak tahun yang dapat ditempuh oleh seseorang sejak lahir di Kabupaten Bangka.',
                'satuan' => 'Tahun',
                'metodologi' => 'Perhitungan tabel kematian (life table) dari data Susenas BPS & SP2020.',
                'jadwal_rilis' => 'Tahunan (Desember)',
            ],
            'column' => [
                'key' => 'puskesmas_faskes',
                'label' => 'Fasilitas Kesehatan Aktif',
                'unit' => 'Unit',
                'digits' => 0,
            ],
        ],
        'pendidikan' => [
            'name' => 'Harapan Lama Sekolah (HLS)',
            'short_name' => 'Harapan Lama Sekolah',
            'unit' => 'Tahun',
            'value' => 13.08,
            'yoy_change' => 0.12,
            'trend' => [
                ['year' => 2020, 'value' => 12.65],
                ['year' => 2021, 'value' => 12.78],
                ['year' => 2022, 'value' => 12.92],
                ['year' => 2023, 'value' => 13.02],
                ['year' => 2024, 'value' => 13.08],
            ],
            'metadata' => [
                'produsen' => 'BPS Kabupaten Bangka & Dindikpora Kab. Bangka',
                'definisi' => 'Lamanya sekolah (dalam tahun) yang diharapkan akan dirasakan oleh anak pada umur 7 tahun di masa mendatang.',
                'satuan' => 'Tahun',
                'metodologi' => 'Survei Sosial Ekonomi Nasional (Susenas) BPS.',
                'jadwal_rilis' => 'Tahunan (Desember)',
            ],
            'column' => [
                'key' => 'sekolah_total',
                'label' => 'Sekolah (SD/SMP/SMA)',
                'unit' => 'Unit',
                'digits' => 0,
            ],
        ],
        'pertanian' => [
            'name' => 'Produksi Padi & Kelapa Sawit Kabupaten Bangka',
            'short_name' => 'Produksi Pangan/Perkebunan',
            'unit' => 'Ribu Ton',
            'value' => 218.45,
            'yoy_change' => 3.20,
            'trend' => [
                ['year' => 2020, 'value' => 192.10],
                ['year' => 2021, 'value' => 198.60],
                ['year' => 2022, 'value' => 205.40],
                ['year' => 2023, 'value' => 211.68],
                ['year' => 2024, 'value' => 218.45],
            ],
            'metadata' => [
                'produsen' => 'Dinas Pangan & Pertanian Kab. Bangka & BPS',
                'definisi' => 'Total volume panen komoditas pangan pokok (padi sawah/ladang) dan perkebunan rakyat di wilayah Kab. Bangka.',
                'satuan' => 'Ribu Ton / Tahun',
                'metodologi' => 'Kerangka Sampel Area (KSA) BPS & laporan Dinas Pertanian.',
                'jadwal_rilis' => 'Tahunan (Februari)',
            ],
            'column' => [
                'key' => 'lahan_tani',
                'label' => 'Luas Panen Pertanian/Kebun',
                'unit' => 'Hektar',
                'digits' => 0,
            ],
        ],
        'sosial' => [
            'name' => 'Cakupan Penerima Jaminan Sosial (DTKS/PBI)',
            'short_name' => 'Bantuan Sosial Terdaftar',
            'unit' => 'Keluarga',
            'value' => 31250,
            'yoy_change' => -1.80,
            'trend' => [
                ['year' => 2020, 'value' => 35400],
                ['year' => 2021, 'value' => 34100],
                ['year' => 2022, 'value' => 32800],
                ['year' => 2023, 'value' => 31820],
                ['year' => 2024, 'value' => 31250],
            ],
            'metadata' => [
                'produsen' => 'Dinas Sosial Kab. Bangka & Kemensos RI',
                'definisi' => 'Jumlah Keluarga Penerima Manfaat (KPM) bantuan sosial terverifikasi dalam Data Terpadu Kesejahteraan Sosial (DTKS).',
                'satuan' => 'Keluarga / KPM',
                'metodologi' => 'Pemutakhiran Data Mandiri SIKS-NG berbasis NIK Dukcapil.',
                'jadwal_rilis' => 'Semesteran',
            ],
            'column' => [
                'key' => 'penerima_bansos',
                'label' => 'Penerima Bantuan Sosial',
                'unit' => 'Keluarga',
                'digits' => 0,
            ],
        ],
    ],

    // 8 Kecamatan Kabupaten Bangka (Data BPS 2024 / Kabupaten Bangka Dalam Angka)
    'kecamatan' => [
        [
            'id' => 'sungailiat',
            'name' => 'Sungailiat',
            'capital' => 'Sungailiat (Ibu Kota)',
            'area_km2' => 144.38,
            'population' => 95866,
            'density' => 664,
            'pdrb_kapita' => 76.50,
            'angkatan_kerja' => 48200,
            'puskesmas_faskes' => 18,
            'sekolah_total' => 64,
            'lahan_tani' => 2450,
            'penerima_bansos' => 6820,
        ],
        [
            'id' => 'belinyu',
            'name' => 'Belinyu',
            'capital' => 'Belinyu',
            'area_km2' => 545.92,
            'population' => 52140,
            'density' => 96,
            'pdrb_kapita' => 68.20,
            'angkatan_kerja' => 26400,
            'puskesmas_faskes' => 12,
            'sekolah_total' => 45,
            'lahan_tani' => 6800,
            'penerima_bansos' => 4950,
        ],
        [
            'id' => 'mendo-barat',
            'name' => 'Mendo Barat',
            'capital' => 'Petaling',
            'area_km2' => 574.44,
            'population' => 51920,
            'density' => 90,
            'pdrb_kapita' => 58.40,
            'angkatan_kerja' => 25800,
            'puskesmas_faskes' => 10,
            'sekolah_total' => 38,
            'lahan_tani' => 9400,
            'penerima_bansos' => 4890,
        ],
        [
            'id' => 'pemali',
            'name' => 'Pemali',
            'capital' => 'Air Duren',
            'area_km2' => 128.53,
            'population' => 35790,
            'density' => 278,
            'pdrb_kapita' => 66.10,
            'angkatan_kerja' => 17900,
            'puskesmas_faskes' => 8,
            'sekolah_total' => 28,
            'lahan_tani' => 3850,
            'penerima_bansos' => 3420,
        ],
        [
            'id' => 'merawang',
            'name' => 'Merawang',
            'capital' => 'Baturusa',
            'area_km2' => 204.93,
            'population' => 32480,
            'density' => 159,
            'pdrb_kapita' => 65.80,
            'angkatan_kerja' => 16200,
            'puskesmas_faskes' => 9,
            'sekolah_total' => 29,
            'lahan_tani' => 4200,
            'penerima_bansos' => 3180,
        ],
        [
            'id' => 'riau-silip',
            'name' => 'Riau Silip',
            'capital' => 'Riau',
            'area_km2' => 521.80,
            'population' => 29610,
            'density' => 57,
            'pdrb_kapita' => 59.20,
            'angkatan_kerja' => 14800,
            'puskesmas_faskes' => 7,
            'sekolah_total' => 26,
            'lahan_tani' => 7600,
            'penerima_bansos' => 2980,
        ],
        [
            'id' => 'puding-besar',
            'name' => 'Puding Besar',
            'capital' => 'Puding',
            'area_km2' => 373.10,
            'population' => 24792,
            'density' => 66,
            'pdrb_kapita' => 57.10,
            'angkatan_kerja' => 12400,
            'puskesmas_faskes' => 6,
            'sekolah_total' => 22,
            'lahan_tani' => 6100,
            'penerima_bansos' => 2610,
        ],
        [
            'id' => 'bakam',
            'name' => 'Bakam',
            'capital' => 'Bakam',
            'area_km2' => 482.90,
            'population' => 19460,
            'density' => 40,
            'pdrb_kapita' => 55.60,
            'angkatan_kerja' => 9800,
            'puskesmas_faskes' => 5,
            'sekolah_total' => 18,
            'lahan_tani' => 5900,
            'penerima_bansos' => 2400,
        ],
    ],

    // Dataset Rujukan Terkait (Katalog SDI Bangka)
    'featured_datasets' => [
        [
            'id' => 'ds-01',
            'title' => 'Statistik Kependudukan & Proyeksi Penduduk per Kecamatan Kab. Bangka 2020–2024',
            'category' => 'Kependudukan',
            'opd' => 'Dinas Kependudukan dan Pencatatan Sipil Kab. Bangka',
            'updated_at' => '15 Januari 2025',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
        [
            'id' => 'ds-02',
            'title' => 'Indikator PDRB & Pertumbuhan Ekonomi Lapangan Usaha Kab. Bangka 2020–2024',
            'category' => 'Perekonomian',
            'opd' => 'Badan Pusat Statistik (BPS) & Bappeda Kab. Bangka',
            'updated_at' => '02 Februari 2025',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
        [
            'id' => 'ds-03',
            'title' => 'Capaian Indeks Pembangunan Manusia (IPM) & Dimensi Pembentuk Kab. Bangka 2024',
            'category' => 'Pendidikan & Kesehatan',
            'opd' => 'Bappeda Kabupaten Bangka',
            'updated_at' => '10 Desember 2024',
            'url' => 'https://satudata.bangka.go.id/dataset',
        ],
    ],
];
